### ISSUE TITLE
Add processing scripts to the shared resources

### ISSUE THREAD

**Issue by elpaso** [akbargumbira/qgis_symbology_sharing#11]
Nice to have

**Comment by akbargumbira** [comment]
Is it only a matter of adding a directory or there is a mechanism needed to do to 'import' the script like svg, symbol, and colorramps?

**Comment by volaya** [comment]
The script should be copied to the scripts folder and then the script provider should be refreshed. You can see here how that is done by the "add script from file" functionality that is available in the Toolbox:

https://github.com/qgis/QGIS/blob/master/python/plugins/processing/script/AddScriptFromFileAction.py

Let me know if you have questions

**Comment by akbargumbira** [comment]
I quickly added the handler for processing scriipt in here in processing branch (https://github.com/akbargumbira/qgis_symbology_sharing/commit/5e883611088965c51e0dd5f73fcd342adb6d21a3) But I couldn't import alglist even using QGIS 2.16 (I just tried in python console, it throws an error too). I see that the module is rather new (in 2.14 it's still in ToolBox). I'll look more about it this week

```
from processing.core.alglist import algList
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/qgis-2.16/share/qgis/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named alglist
```

**Comment by akbargumbira** [comment]
I am closing this. It's implemented now in master branch. Processing scripts should be put under ```processing``` directory. The script will be added with name: ```<filename> (<collection id>)``` to avoid name collision between scripts from different collections

**Comment by akbargumbira** [comment]
The problem I had before was only because I had path to different processing directory and it was loaded first
